// SPDX-FileCopyrightText: Copyright 2026 NeXoEmu Project
// SPDX-License-Identifier: GPL-3.0-or-later
// Adapted from RaptorCitrus for NeXoEmu (Eden-based emulator).
// Uses OpenSSL RAND_bytes (already a dependency of Eden) instead of mbedtls.

#include "common/hardware_id.h"

#include <cstdio>
#include <cstdlib>
#include <string>

#include <openssl/rand.h>

#ifdef _WIN32
#include <windows.h>
#endif

namespace Common {

namespace {

// Alphabet for the ID: 62 characters (0-9, A-Z, a-z)
constexpr const char ALPHABET[] =
    "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

// ID length: 48 characters
constexpr std::size_t ID_LENGTH = 0x30;

// Fallback ID used if generation fails
constexpr const char INVALID[] = "NEXOEMU-RAPTOR-NETWORK-INVALID-HWID-00000000";

#ifdef _WIN32
// Registry key for Windows storage
constexpr const char REG_KEY[]   = R"(SOFTWARE\NexoEmu\RaptorNetwork)";
constexpr const char REG_VALUE[] = "HardwareID";
#endif

/// Generates a new 48-character random hardware ID using OpenSSL RAND_bytes.
/// Each character is chosen from ALPHABET (62 chars) to avoid modulo bias
/// we use 64 bytes of randomness (one byte per character) and take value % 62.
std::string GenerateID() {
    std::string new_id(ID_LENGTH, '\0');
    // Generate ID_LENGTH random bytes
    std::vector<unsigned char> buf(ID_LENGTH);
    if (RAND_bytes(buf.data(), static_cast<int>(ID_LENGTH)) != 1) {
        return INVALID;
    }
    for (std::size_t i = 0; i < ID_LENGTH; ++i) {
        new_id[i] = ALPHABET[buf[i] % 62];
    }
    return new_id;
}

} // namespace

// ============================================================
// Windows implementation: stores the ID in the Windows Registry
// ============================================================
#ifdef _WIN32

namespace {

std::string GetRaptorHardwareIDImpl() {
    HKEY key{};
    if (RegCreateKeyA(HKEY_CURRENT_USER, REG_KEY, &key) != ERROR_SUCCESS) {
        return INVALID;
    }

    DWORD data_size{};
    const auto res = RegGetValueA(key, nullptr, REG_VALUE, RRF_RT_REG_SZ,
                                  nullptr, nullptr, &data_size);
    if (res != ERROR_SUCCESS || data_size < (ID_LENGTH + 1)) {
        // Not found or too short — generate and store a new one
        auto new_id = GenerateID();
        RegSetKeyValueA(key, nullptr, REG_VALUE, REG_SZ,
                        new_id.c_str(), static_cast<DWORD>(new_id.size()));
        RegCloseKey(key);
        return new_id;
    }

    std::string out(data_size, '\0');
    if (RegGetValueA(key, nullptr, REG_VALUE, RRF_RT_REG_SZ,
                     nullptr, out.data(), &data_size) != ERROR_SUCCESS) {
        RegCloseKey(key);
        return INVALID;
    }
    RegCloseKey(key);
    out.resize(data_size - 1);
    return out;
}

} // namespace

// ============================================================
// Linux / macOS / other POSIX: stores the ID in ~/.raptor_id
// ============================================================
#else

namespace {

std::string GetRaptorHardwareIDImpl() {
    // Build path: $HOME/.raptor_id
    const char* home = std::getenv("HOME");
    std::string filepath = home ? (std::string(home) + "/.raptor_id") : "/tmp/.raptor_id";

    // Try to read existing ID
    auto* file = std::fopen(filepath.c_str(), "r");
    if (file == nullptr) {
        // Create a new one
        auto* write_file = std::fopen(filepath.c_str(), "w");
        if (write_file == nullptr) {
            return INVALID;
        }
        auto new_id = GenerateID();
        std::fputs(new_id.c_str(), write_file);
        std::fputs("\n\n# DO NOT EDIT - Generated by NeXoEmu for Raptor Network auth\n",
                   write_file);
        std::fclose(write_file);
        return new_id;
    }

    // Verify the file has at least ID_LENGTH bytes
    std::fseek(file, 0, SEEK_END);
    const long size = std::ftell(file);
    if (size < static_cast<long>(ID_LENGTH)) {
        std::fclose(file);
        return INVALID;
    }

    std::fseek(file, 0, SEEK_SET);
    std::string out(ID_LENGTH, '\0');
    std::fread(out.data(), 1, ID_LENGTH, file);
    std::fclose(file);
    return out;
}

} // namespace

#endif // _WIN32

/// Public API: returns the hardware ID, computed once and cached.
const std::string& GetRaptorHardwareID() {
    static const std::string id = GetRaptorHardwareIDImpl();
    return id;
}

} // namespace Common
